# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: easy_model 2.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "easy_model"
  s.version = "2.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["SUZUKI Kei"]
  s.date = "2013-12-12"
  s.description = "    EasyModel provides features of database independent attribute.\n    You can define the attribute like ActiveRecord that perform data conversion during assignment.\n    \u{30c7}\u{30fc}\u{30bf}\u{30d9}\u{30fc}\u{30b9}\u{306b}\u{95a2}\u{9023}\u{4ed8}\u{304b}\u{306a}\u{3044}\u{5c5e}\u{6027}\u{3092}\u{5b9a}\u{7fa9}\u{3059}\u{308b}\u{6a5f}\u{80fd}\u{3092}\u{63d0}\u{4f9b}\u{3057}\u{307e}\u{3059}.\n    \u{4ee3}\u{5165}\u{6642}\u{306b} ActiveRecord \u{3068}\u{540c}\u{69d8}\u{306e}\u{578b}\u{5909}\u{63db}\u{304c}\u{884c}\u{308f}\u{308c}\u{308b}\u{5c5e}\u{6027}\u{3092}\u{5b9a}\u{7fa9}\u{3059}\u{308b}\u{3053}\u{3068}\u{304c}\u{3067}\u{304d}\u{307e}\u{3059}.\n"
  s.email = "info-techscore@synergy101.jp"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc",
    "README_ja.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "README_ja.rdoc",
    "Rakefile",
    "VERSION",
    "easy_model.gemspec",
    "lib/easy_model.rb",
    "lib/easy_model/base.rb",
    "lib/easy_model/column.rb",
    "lib/easy_model/column_for_active_model.rb",
    "lib/easy_model/column_for_active_record.rb",
    "lib/easy_model/search_form.rb",
    "test/easy_model/ja.yml",
    "test/easy_model/test_column_for_active_model.rb",
    "test/easy_model/test_column_for_active_record.rb",
    "test/easy_model/test_search_form.rb",
    "test/helper.rb"
  ]
  s.homepage = "http://github.com/techscore/easy_model"
  s.licenses = ["BSD"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "EasyModel provides features of database independent attribute. \u{30c7}\u{30fc}\u{30bf}\u{30d9}\u{30fc}\u{30b9}\u{306b}\u{95a2}\u{9023}\u{4ed8}\u{304b}\u{306a}\u{3044}\u{5c5e}\u{6027}\u{3092}\u{5b9a}\u{7fa9}\u{3059}\u{308b}\u{6a5f}\u{80fd}\u{3092}\u{63d0}\u{4f9b}\u{3057}\u{307e}\u{3059}."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, ["~> 4.0"])
      s.add_runtime_dependency(%q<activerecord>, ["~> 4.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
    else
      s.add_dependency(%q<activemodel>, ["~> 4.0"])
      s.add_dependency(%q<activerecord>, ["~> 4.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    end
  else
    s.add_dependency(%q<activemodel>, ["~> 4.0"])
    s.add_dependency(%q<activerecord>, ["~> 4.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
  end
end

